apiVersion: v1
data:
  MYSQL_DATABASE: {{ .Values.db.secrets.MYSQL_DATABASE | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.db.secrets.MYSQL_PASSWORD | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.db.secrets.MYSQL_ROOT_PASSWORD | b64enc | quote }}
  MYSQL_USER: {{ .Values.db.secrets.MYSQL_USER | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-creds
  namespace: {{ .Values.namespace }}
type: Opaque