apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicemysql.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mysql.deployment_app }}
spec:
  ports:
    - port: {{ .Values.servicemysql.port }}
      protocol: {{ .Values.servicemysql.protocol }}
      targetPort: {{ .Values.servicemysql.target_port }}
  selector:
    app: {{ .Values.mysql.deployment_app }}
  clusterIP: None
