apiVersion: v1
data:
  WORDPRESS_DB_HOST: {{ .Values.wordpress.secrets.WORDPRESS_DB_HOST | b64enc | quote }}
  WORDPRESS_DB_NAME: {{ .Values.wordpress.secrets.WORDPRESS_DB_NAME | b64enc | quote }}
  WORDPRESS_DB_PASSWORD: {{ .Values.wordpress.secrets.WORDPRESS_DB_PASSWORD | b64enc | quote }}
  WORDPRESS_DB_USER: {{ .Values.wordpress.secrets.WORDPRESS_DB_USER | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-wordpress-creds
  namespace: {{ .Values.namespace }}
type: Opaque