replicaCount: 1

namespace: bitcot

imagePullSecrets: 
  - name: 

imageCredentials:
  registry: 
  username: 
  password:
  email:

accessModes: 
  - ReadWriteOnce

imagePullPolicy: Always

storage: 3Gi

wordpress:
  tier: frontend
  service:
    port: 80
    targetPort: 80
    protocol: TCP
    type: LoadBalancer
  image: wordpress:5.3
  resources:
    requests:
      memory: "500Mi"
      cpu: "600m"
    limits:
      memory: "600Mi"
      cpu: "750m"
  secrets:
    WORDPRESS_DB_HOST: bitcot-mysql
    WORDPRESS_DB_NAME: know2
    WORDPRESS_DB_PASSWORD: groot
    WORDPRESS_DB_USER: wp_root
  containerPort: 80
  containerPorthttps: 443
  Volumes:
    name: wordpress-persistent-storage
    mountPath: /var/www/html

Sidecar:
  name: sidecar-container
  image: ubuntu:20.04

db:
  tier: mysql
  service:
    port: 3306
    targetPort: 3306
    protocol: TCP
    type: ClusterIP
  image: mysql:5.6
  resources:
    requests:
      memory: "500Mi"
      cpu: "600m"
    limits:
      memory: "600Mi"
      cpu: "750m"
  secrets:
    MYSQL_DATABASE: know2
    MYSQL_PASSWORD: groot
    MYSQL_ROOT_PASSWORD: groot
    MYSQL_USER: wp_root
  containerPort: 3306
  Volumes:
    name: mysql-persistent-storage
    mountPath: /var/lib/mysql

initContainers:
  name: init-container-mysql
  image: mysql:latest
  Volume:
    name: db-dump
    mountPath: /docker-entrypoint-initdb.d